// 版权没有，拷贝自由。

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

// namespace AuraAttributeTags
// {
// 	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Health);
// 	UE_DECLARE_GAMEPLAY_TAG_EXTERN(MaxHealth);
// 	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mana);
// 	UE_DECLARE_GAMEPLAY_TAG_EXTERN(MaxMana);
// }

namespace Attributes
{
	namespace Primary
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Strength);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Intelligence);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Resilience);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Vigor);
	}

	namespace Secondary
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Armor);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(ArmorPenetration);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(BlockChance);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(CriticalHitChance);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(CriticalHitDamage);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(CriticalHitResistance);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(HealthRegeneration);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(ManaRegeneration);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(MaxHealth);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(MaxMana);

	}
	namespace Vital
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Health);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mana);
	}
}

namespace Message
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tag);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(HealthPotion);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(HealthCrystal);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ManaPotion);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ManaCrystal);
}

// input tags
namespace InputAction
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(LMB);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(RMB);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(_1);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(_2);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(_3);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(_4);
}

namespace Incoming
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage);
}


namespace Event
{
	namespace Montage
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(FireBolt);
	}
}

namespace Effects
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(HitReaction);
}